#!/system/bin/sh
SETTINGS_PACKAGE_RDNS=android.settings
echo '中文： 设置存储, English: Setup storage'
termux-setup-storage
TERMUX_DATA=package:com.termux
echo -n '中文： 设置悬浮窗权限 (请按回车), English: Setup "draw over apps" (Press "Enter")'
read i
am start -a $SETTINGS_PACKAGE_RDNS.action.MANAGE_OVERLAY_PERMISSION -d $TERMUX_DATA > /dev/null
echo -n '中文： 设置禁用电池优化 (请按回车), English: Setup "ignore battery optimizations" (Press "Enter")'
read i
am start -a $SETTINGS_PACKAGE_RDNS.IGNORE_BATTERY_OPTIMIZATION_SETTINGS > /dev/null
echo -n '中文： 设置关联启动与后台弹出权限 (请按回车), English: Setup "Startup & Background pop-ups permissions" (Press "Enter")'
read i
am start -a $SETTINGS_PACKAGE_RDNS.APPLICATION_DETAILS_SETTINGS -d $TERMUX_DATA > /dev/null
echo '中文： 设置allow-external-app, English: Setup "allow-external-app"'
termux_properties_path=/data/data/com.termux/files/home/.termux/termux.properties
if [ -f $termux_properties_path ]
then awk '/^#/{print
next }/^\s*allow-external-apps/{gsub(/allow-external-apps.*/,"allow-external-apps=true")
found=1}{print $0}END{if(!found)print "allow-external-apps=true"}' $termux_properties_path > "$TMPDIR"/a.tmp && \
	mv "$TMPDIR"/a.tmp $termux_properties_path
else mkdir -p $(dirname $termux_properties_path)
echo 'allow-external-apps=true' > $termux_properties_path
fi
echo '中文： 安装CLang, English: Install CLang'
pkg i clang -y
apt autoremove --purge
apt clean
echo ok
